var axios = require('axios');
var fs = require('fs');

var runningProcesses = [];
setInterval(async () => {
    if (runningProcesses.length > 0) {
        var index = 0;
        while (index < runningProcesses.length) {
            index++
            var getGenerationStatus = await axios.get(runningProcesses[index - 1].url);

            if (getGenerationStatus.data.status == 200) {
                const tempProcess = runningProcesses
                runningProcesses = runningProcesses.filter(x => x.url != tempProcess[index - 1].url);

                var mediaPath = "./src/Thena" + Math.floor(Math.random() * 100) + ".png";
                fs.writeFileSync(mediaPath, getGenerationStatus.data.image, 'base64');
                
                try { await tempProcess[index - 1].sock.sendMessage(tempProcess[index - 1].groupId, { delete: tempProcess[index - 1].messageId })} catch {}
                try { await tempProcess[index - 1].sock.sendMessage(tempProcess[index - 1].groupId, { image: { url: mediaPath }, caption: tempProcess[index - 1].caption })} catch {
                    try {
                        await tempProcess[index - 1].sock.sendMessage(tempProcess[index - 1].groupId, { image: { url: mediaPath }, caption: "*✨ Image generated by Thena AI*" })
                    } catch {
                    }
                }

                try { fs.unlinkSync(mediaPath)} catch {}
            } else {
                if (getGenerationStatus.data.status != 202) {
                    const tempProcess = runningProcesses
                    runningProcesses = runningProcesses.filter(x => x.url != tempProcess[index - 1].url);
    
                    try { await tempProcess[index - 1].sock.sendMessage(tempProcess[index - 1].groupId, { delete: tempProcess[index - 1].messageId })} catch {}
                    await tempProcess[index - 1].sock.sendMessage(tempProcess[index - 1].groupId, { text: "_❌ Generation failed!_" });
                }
            } 
        }
    }
}, 8000)

addCommand({ pattern: "^dream ?(.*)", access: "all", desc: "_Generate an image using Thena API._", usage: global.handlers[0] + "dream <text> <model> <ratio> <mode>", pluginVersion: "1.0.6", pluginId: "image-generation" }, async (msg, match, sock, rawMessage) => {
    if (!global.database.thenaAPIKey && !String(match[1]).includes("addAPI")) {
        if (msg.key.fromMe) {
            return await sock.sendMessage(msg.key.remoteJid, { text: "_🔐 You need to set your Thena API Key first._\n\n_Use_ ```" + global.handlers[0] + "dream addAPI <your-api-key>``` _to set it._\n\n_To obtain API Key, please visit here: https://t.me/ThenaAIBot?start=refAPI_", edit: msg.key });
        } else {
            return await sock.sendMessage(msg.key.remoteJid, { text: "_❌ The bot owner hasn't added an API key to use this command! Please contact the bot owner._" }, { quoted: rawMessage.messages[0] });
        }
    }
    
    var text = match[1];
    if (!text) {
        if (msg.key.fromMe) {
            return await sock.sendMessage(msg.key.remoteJid, { text: "_🔤 You need to provide a text to generate an image._\n\n_Example ::_ ```" + global.handlers[0] + "dream <text> <model> <ratio> <mode>```" + "\n\n_Models ::_ ```-real || -movie || -anime```\n_Ratio ::_ ```1:1 || 3:4 || 9:16 || 4:3 || 16:9```\n_Mode ::_ ```-fast || -quality```", edit: msg.key });
        } else {
            return await sock.sendMessage(msg.key.remoteJid, { text: "_🔤 You need to provide a text to generate an image._\n\n_Example ::_ ```" + global.handlers[0] + "dream <text> <model> <ratio> <mode>```" + "\n\n_Models ::_ ```-real || -movie || -anime```\n_Ratio ::_ ```1:1 || 3:4 || 9:16 || 4:3 || 16:9```" }, { quoted: rawMessage.messages[0] });
        }
    };

    if (text.includes("addAPI") && msg.key.fromMe) {
        const apiKey = match[1].replace("addAPI ", "").replace(/ /gmi, "");
        if (!apiKey) {
            return await sock.sendMessage(msg.key.remoteJid, { text: "_❌ You need to provide an API key to add._\n\n_Use_ ```" + global.handlers[0] + "dream addAPI <your-api-key>``` _to add it._\n\n_To obtain API Key, please visit here: https://t.me/ThenaAIBot?start=refAPI_", edit: msg.key });
        }
        global.database.thenaAPIKey = apiKey;
        return await sock.sendMessage(msg.key.remoteJid, { text: "_✅ API key added successfully._", edit: msg.key });
    }

    const model = match[1].includes("-real") ? "real" : (match[1].includes("-movie") ? "movie" : (match[1].includes("-anime") ? "anime" : "real"));
    const ratio = match[1].includes("3:4") ? "3:4" : (match[1].includes("9:16") ? "9:16" : (match[1].includes("4:3") ? "4:3" : (match[1].includes("16:9") ? "16:9" : "1:1")));
    const mode = match[1].includes("-fast") ? "fast" : "quality";

    var modelText = model == "real" ? "Photoreal" : (model == "movie" ? "Movie" : "Anime");
    const ratioMapping = {
        "1:1": { width: 1024, height: 1024 },
        "3:4": { width: 768, height: 1024 },
        "9:16": { width: 576, height: 1024 },
        "4:3": { width: 1024, height: 768 },
        "16:9": { width: 1024, height: 576 }
    }

    const dimensions = ratioMapping[ratio] || { width: 1024, height: 1024 }
    const tempGroupId = msg.key.remoteJid;

    const payload = {
        "prompt": text.replace(model, "").replace(ratio, ""),
        "model": model === "real" ? "754019 b5df2e e606f1 a7600b 96b0c8 94" : model === "movie" ? "8gg12 61812 6628 19729 6b4a5 5060" : model === "anime" ? "5g72h1 y661hp k771ns 33bb21 77bagl 6b 3090" : "754019 b5df2e e606f1 a7600b 96b0c8 94",
        "creative": false,
        "width": dimensions.width,
        "height": dimensions.height,
        "fastMode": mode === "fast" ? true : false,
        "enhance": true
    }
    var payloadConfig = {
        method: 'post',
        url: 'https://create.thena.workers.dev/create_image_thena_v5',
        headers: { 
           'User-Agent': global.database.thenaAPIKey,
           'Content-Type': 'application/json'
        },
        data : payload
    };

    var result = await axios(payloadConfig);
    
    if (result.data.status == 200) {
        if (msg.key.fromMe) {
            await sock.sendMessage(msg.key.remoteJid, { text: "_🔄️ Image generating.._", edit: msg.key });
        } else {
            var publicMessage = await sock.sendMessage(msg.key.remoteJid, { text: "_🔄️ Image generating.._" }, { quoted: rawMessage.messages[0] });
        }

        runningProcesses.push({
            url: "https://create.thena.workers.dev/status?id=" + result.data.image,
            messageId: msg.key.fromMe ? msg.key : publicMessage.key,
            groupId: tempGroupId,
            caption: "*✨ Image generated by Thena AI*\n\n_Model ::_ ```" + modelText + "```" + "\n_Prompt ::_ ```" + text + "```",
            sock: sock,
        })
        return;
    } else {
        if (msg.key.fromMe) {
            return await sock.sendMessage(msg.key.remoteJid, { text: "_❌ Failed to generate image._\n\n_Error: " + result.data.content + "_\n\n_Please try again later._", edit: msg.key });
        } else {
            return await sock.sendMessage(msg.key.remoteJid, { text: "_❌ Failed to generate image._\n\n_Error: " + result.data.content + "_\n\n_Please try again later._" }, { quoted: rawMessage.messages[0] });
        }
    }
})